simulation_end_time_ns=2000000000
simulation_seed=123456789

satellite_network_dir="../../../../satellite_networks_state/gen_data/25x25_algorithm_ucb_distributed_routing"
satellite_network_routes_dir="../../../../satellite_networks_state/gen_data/25x25_algorithm_ucb_distributed_routing"
dynamic_state_update_interval_ns=100000000

isl_data_rate_megabit_per_s=10.0
gsl_data_rate_megabit_per_s=10.0
isl_max_queue_size_pkts=100
gsl_max_queue_size_pkts=100

enable_isl_utilization_tracking=true
isl_utilization_tracking_interval_ns=1000000000

tcp_socket_type=TcpVegas
satellite_network_routing=spf_dynamic
ucb_slot_duration_s=0.1
max_gsl_length_m=1089686.0000000000
max_isl_length_m=1000000000.0000000000

enable_tcp_flow_scheduler=true
tcp_flow_schedule_filename="schedule.csv"
tcp_flow_enable_logging_for_tcp_flow_ids=set(0)
