simulation_end_time_ns=200000000000
simulation_seed=123456789

satellite_network_dir="../../../../paper/satellite_networks_state/gen_data/kuiper_630_isls_plus_grid_ground_stations_top_100_algorithm_ucb_distributed_routing"
satellite_network_routes_dir="../../../../paper/satellite_networks_state/gen_data/kuiper_630_isls_plus_grid_ground_stations_top_100_algorithm_ucb_distributed_routing"
dynamic_state_update_interval_ns=100000000

isl_data_rate_megabit_per_s=10.0
gsl_data_rate_megabit_per_s=10.0
isl_max_queue_size_pkts=100
gsl_max_queue_size_pkts=100

enable_isl_utilization_tracking=true
isl_utilization_tracking_interval_ns=1000000000

tcp_socket_type=TcpNewReno
satellite_network_routing=ucb_distributed
ucb_max_hop_count=30
ucb_slot_duration_s=1.0
ucb_reward_weights=list(0.25,0.25,0.25,0.25)
ucb_epsilon1=1e-9
ucb_epsilon2=1e-9

enable_tcp_flow_scheduler=false

enable_udp_burst_scheduler=true
udp_burst_schedule_filename="../end_to_end/run/udp_burst_schedule.csv"
udp_burst_enable_logging_for_udp_burst_ids=set(0)

enable_pingmesh_scheduler=true
pingmesh_interval_ns=1000000000
pingmesh_endpoint_pairs=all
