simulation_end_time_ns=[SIMULATION-END-TIME-NS]
simulation_seed=123456789

satellite_network_dir="../../../../satellite_networks_state/gen_data/[SATELLITE-NETWORK]"
satellite_network_routes_dir="../../../../satellite_networks_state/gen_data/[SATELLITE-NETWORK]/[DYNAMIC-STATE-DIR]"
satellite_network_force_static=[SATELLITE-NETWORK-FORCE-STATIC]
dynamic_state_update_interval_ns=[DYNAMIC-STATE-UPDATE-INTERVAL-NS]

isl_data_rate_megabit_per_s=[ISL-DATA-RATE-MEGABIT-PER-S]
gsl_data_rate_megabit_per_s=[GSL-DATA-RATE-MEGABIT-PER-S]
isl_max_queue_size_pkts=[ISL-MAX-QUEUE-SIZE-PKTS]
gsl_max_queue_size_pkts=[GSL-MAX-QUEUE-SIZE-PKTS]

enable_isl_utilization_tracking=[ENABLE-ISL-UTILIZATION-TRACKING]
[ISL-UTILIZATION-TRACKING-INTERVAL-NS-COMPLETE]

tcp_socket_type=[TCP-SOCKET-TYPE]
satellite_network_routing=[SATELLITE-NETWORK-ROUTING]
ucb_max_hop_count=[UCB-MAX-HOP-COUNT]
ucb_slot_duration_s=[UCB-SLOT-DURATION-S]
ucb_reward_weights=[UCB-REWARD-WEIGHTS]
ucb_epsilon1=[UCB-EPSILON1]
ucb_epsilon2=[UCB-EPSILON2]
ucb_random_select_prob=[UCB-RANDOM-SELECT-PROB]
ucb_dst_arrival_reward=[UCB-DST-ARRIVAL-REWARD]
ucb_queue_drop_threshold=[UCB-QUEUE-DROP-THRESHOLD]
ucb_reference_delay_ms=[UCB-REFERENCE-DELAY-MS]
ucb_reference_distance_m=[UCB-REFERENCE-DISTANCE-M]
ucb_slot_decay_factor=[UCB-SLOT-DECAY-FACTOR]
max_gsl_length_m=[MAX-GSL-LENGTH-M]
max_isl_length_m=[MAX-ISL-LENGTH-M]

enable_tcp_flow_scheduler=true
tcp_flow_schedule_filename="tcp_flow_schedule.csv"
tcp_flow_enable_logging_for_tcp_flow_ids=[TCP-FLOW-LOG-SET]
